version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "5000:3000" # Port pour le backend (API + fichiers frontend)
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/my_database
      - JWT_SECRET=your_jwt_secret
